<?php
include "../db.php";

if (isset($_POST['export_all_pdf'])) {
    $exportSearchTerm = mysqli_real_escape_string($conn, $_POST['search'] ?? '');
    $exportStart = $_POST['start_date'] ?? '';
    $exportEnd = $_POST['end_date'] ?? '';

    $exportSearchQuery = !empty($exportSearchTerm) ? "AND (name LIKE '%$exportSearchTerm%' OR enrollment_no LIKE '%$exportSearchTerm%')" : '';
    $exportDateFilter = (!empty($exportStart) && !empty($exportEnd)) ? "AND date BETWEEN '$exportStart' AND '$exportEnd'" : '';

    // Fetch all students
    $exportQuery = "SELECT * FROM users WHERE role='student' $exportSearchQuery";
    $exportResult = mysqli_query($conn, $exportQuery);

    require_once 'tcpdf/tcpdf.php';

    class MYPDF extends TCPDF {
        public function Footer() {
            $this->SetY(-15);
            $this->SetFont('helvetica', 'I', 9);
            $this->Cell(0, 10, 'Report generated by Admin | © Light De Literacy', 0, false, 'C');
        }
    }
    $pdf = new MYPDF();
    $pdf->AddPage();
    date_default_timezone_set('Asia/Kolkata');
    $exportDateTime = date('d-m-Y h:i A');

    $pdf->SetFont('helvetica', '', 12);
    $html = "<h2 style='text-align:center;'>All Students Attendance Report</h2>";
    $html .= "<p><strong>Exported On:</strong> {$exportDateTime}</p>";
    $html .= "<table border='1' cellpadding='8' cellspacing='0' style='width:100%; border-collapse:collapse; font-size:11pt;'>
                <thead>
                    <tr style='background-color:#007bff; color:#fff;'>
                        <th style='width:10%;'><strong>S.No</strong></th>
                        <th style='width:35%;'><strong>Name</strong></th>
                        <th style='width:30%;'><strong>Enrollment</strong></th>
                        <th style='width:25%;'><strong>Attendance %</strong></th>
                    </tr>
                </thead><tbody>";

    $sno = 1;
    while ($row = mysqli_fetch_assoc($exportResult)) {
        $totalQuery = mysqli_query($conn, "SELECT COUNT(*) as total FROM attendance WHERE member_id='{$row['id']}' $exportDateFilter");
        $total = mysqli_fetch_assoc($totalQuery)['total'];
        $presentQuery = mysqli_query($conn, "SELECT COUNT(*) as present FROM attendance WHERE member_id='{$row['id']}' AND status='present' $exportDateFilter");
        $present = mysqli_fetch_assoc($presentQuery)['present'];
        $percent = ($total > 0) ? round(($present / $total) * 100, 2) : 0;

        $html .= "<tr>
                    <td>{$sno}</td>
                    <td>{$row['name']}</td>
                    <td>{$row['enrollment_no']}</td>
                    <td>{$percent}%</td>
                  </tr>";
        $sno++;
    }

    $html .= "</tbody></table><br><br>";

    $pdf->writeHTML($html, true, false, true, false, '');
    $pdf->Output('All_Students_Report.pdf', 'D');
    exit();
}

$searchQuery = "";
$dateFilter = "";

if (isset($_POST['search']) && !empty($_POST['search'])) {
    $searchTerm = mysqli_real_escape_string($conn, $_POST['search']);
    $searchQuery = "AND (name LIKE '%$searchTerm%' OR enrollment_no LIKE '%$searchTerm%')";
}

// Set startDate and endDate variables for use in export links and filtering
$startDate = $_POST['start_date'] ?? '';
$endDate = $_POST['end_date'] ?? '';
if (!empty($startDate) && !empty($endDate)) {
    $dateFilter = "AND date BETWEEN '$startDate' AND '$endDate'";
}

$query = "SELECT * FROM users WHERE role='student' $searchQuery";

$result = mysqli_query($conn, $query);

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../assets/style.css">
</head>
<body>
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h3 class="fw-bold">📊 Report Page</h3>
        <div>
            <a href="dashboard.php" class="btn btn-primary">Back to Dashboard</a>
        </div>
    </div>

    <!-- Report Search & Date Filter -->
    <form method="POST" class="mb-4 d-flex gap-2 flex-wrap">
        <input type="text" class="form-control w-auto" name="search" placeholder="Search by name or ID" value="<?= htmlspecialchars($_POST['search'] ?? '') ?>" />
        <input type="date" name="start_date" class="form-control w-auto" />
        <input type="date" name="end_date" class="form-control w-auto" />
        <button type="submit" class="btn btn-primary">Filter</button>
        <button type="submit" name="export_all_pdf" class="btn btn-dark fw-semibold">📥 Export All as PDF</button>
    </form>

    <?php
    // Prepare attendance percentages
    $attendanceData = [];
    $allStudentsQuery = mysqli_query($conn, "SELECT * FROM users WHERE role='student' $searchQuery");
    while ($student = mysqli_fetch_assoc($allStudentsQuery)) {
        $id = $student['id'];
        $name = $student['name'];
        $enrollment = $student['enrollment_no'];

        $totalQuery = mysqli_query($conn, "SELECT COUNT(*) as total FROM attendance WHERE member_id='$id' $dateFilter");
        $total = mysqli_fetch_assoc($totalQuery)['total'] ?? 0;

        $presentQuery = mysqli_query($conn, "SELECT COUNT(*) as present FROM attendance WHERE member_id='$id' AND status='present' $dateFilter");
        $present = mysqli_fetch_assoc($presentQuery)['present'] ?? 0;

        $percent = ($total > 0) ? round(($present / $total) * 100, 2) : 0;

        $attendanceData[] = [
            'name' => $name,
            'enrollment' => $enrollment,
            'percentage' => $percent
        ];
    }

    // Sort by percentage
    usort($attendanceData, fn($a, $b) => $b['percentage'] <=> $a['percentage']);

    $topFive = array_slice($attendanceData, 0, 5);
    $bottomFive = array_slice($attendanceData, -5);
    ?>

    <div class="row mb-4">
      <div class="col-md-6">
        <h5>🏆 Top 5 Best Attendance</h5>
        <ul class="list-group">
          <?php foreach ($topFive as $student): ?>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <?= htmlspecialchars($student['name']) ?> (<?= $student['enrollment'] ?>)
              <span class="badge bg-success"><?= $student['percentage'] ?>%</span>
            </li>
          <?php endforeach; ?>
        </ul>
      </div>
      <div class="col-md-6">
        <h5>⚠️ Bottom 5 Attendance</h5>
        <ul class="list-group">
          <?php foreach ($bottomFive as $student): ?>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <?= htmlspecialchars($student['name']) ?> (<?= $student['enrollment'] ?>)
              <span class="badge bg-danger"><?= $student['percentage'] ?>%</span>
            </li>
          <?php endforeach; ?>
        </ul>
      </div>
    </div>

    <!-- Attendance Table -->
    <div class="table-responsive">
    <table class="table table-striped mb-0" style="margin-right: 0;">
        <thead>
            <tr>
                <th>Name</th>
                <th>Enrollment No</th>
                <th>Attendance %</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php while ($row = mysqli_fetch_assoc($result)): ?>
                <?php
                $totalQuery = mysqli_query($conn, "SELECT COUNT(*) as total FROM attendance WHERE member_id='{$row['id']}' $dateFilter");
                $total = mysqli_fetch_assoc($totalQuery)['total'];

                $presentQuery = mysqli_query($conn, "SELECT COUNT(*) as present FROM attendance WHERE member_id='{$row['id']}' AND status='present' $dateFilter");
                $present = mysqli_fetch_assoc($presentQuery)['present'];

                $percent = ($total > 0) ? round(($present / $total) * 100, 2) : 0;
                ?>
                <tr>
                    <td><?= $row['name'] ?></td>
                    <td><?= $row['enrollment_no'] ?></td>
                    <td><?= $percent ?>%</td>
                    <td>
                        <div class="d-flex flex-wrap gap-1">
                            <a href="export_report.php?enrollment_no=<?= $row['enrollment_no'] ?>&start_date=<?= $startDate ?>&end_date=<?= $endDate ?>&export_type=csv" class="btn btn-sm btn-success">CSV</a>
                            <a href="export_report.php?enrollment_no=<?= $row['enrollment_no'] ?>&start_date=<?= $startDate ?>&end_date=<?= $endDate ?>&export_type=pdf" class="btn btn-sm btn-danger">PDF</a>
                            <a href="attendance_history.php?enrollment_no=<?= urlencode($row['enrollment_no']) ?>" class="btn btn-sm btn-info">History</a>
                        </div>
                    </td>
                </tr>
            <?php endwhile; ?>
        </tbody>
    </table>
    </div>
</div>
</body>
</html>